### ISSUE TITLE
FT Is Not Reporting Out Correct strategy_version value

### ISSUE THREAD

**Issue by Justin2172021** [crashzanders/AutoUpdateNFIX2#1]
After this script is ran, the strategy_version value that FT reports out is not the same as the value represented in the updated strat file that was just pushed.  I have to manually run reload_config either via Telegram or the GUI in order for FT to report out the correct value for strategy_version.  Is this a bug?  Or is this not an issue?  TIA

**Comment by crashzanders** [comment]
Are you sure you have configured the location of the docker-compose in the settings and put the crontab in "sudo". If you have used the same cron as the one presented in the readme, can you provide me with a log excerpt having an update in the file /var/log/logs_update_strategie.log STP?
I use this script on different servers and I don't get this error:
![image](https://user-images.githubusercontent.com/6603832/231974145-7db97644-c18d-41c3-8a1e-e3e769e3453c.png)
![image](https://user-images.githubusercontent.com/6603832/231974231-695abd34-0734-4c5e-ae1d-217796e6e72e.png)

**Comment by Justin2172021** [comment]
I will dm it to you on discord.

**Comment by crashzanders** [comment]
After exchanging, it was an error in the adaptation of the script. If it is the "compose" function of docker which is used and not the "docker-compose" application it is necessary to adapt the script in this way: command = "cd /ft_userdata/ && /usr/bin/docker compose restart".
